#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1

sidebar:
    about: True # set to False or comment line if you want to remove the "how to use?" in the sidebar
    education: True # set to False if you want education in main section instead of in sidebar

    # Profile information
    name: Haena Song
    tagline: Master Student of CSDL
    avatar: 001 송해나.jpg #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

    # Sidebar links
    email: hello@webjeda.com
    phone: 012 345 6789
    website: blog.webjeda.com #do not add http://
    linkedin: alandoe
    github: sharu725
    telegram: # add your nickname without '@' sign
    gitlab:
    bitbucket:
    twitter: '@webjeda'
    stack-overflow: # Number/Username, e.g. 123456/alandoe
    codewars:
    goodreads: # Number-Username, e.g. 123456-alandoe

    languages:
      - idiom: English
        level: Native

      - idiom: French
        level: Professional

      - idiom: Spanish
        level: Professional

    interests:
      - item: Climbings
        link:

      - item: Snowboarding
        link:

      - item: Cooking
        link:



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
